// Code generated by protoc-gen-go. DO NOT EDIT.
// source: google/cloud/securitycenter/v1/source.proto

package securitycenter // import "google.golang.org/genproto/googleapis/cloud/securitycenter/v1"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Cloud Security Command Center's (Cloud SCC) finding source. A finding source
// is an entity or a mechanism that can produce a finding. A source is like a
// container of findings that come from the same scanner, logger, monitor, etc.
type Source struct {
	// The relative resource name of this source. See:
	// https://cloud.google.com/apis/design/resource_names#relative_resource_name
	// Example:
	// "organizations/123/sources/456"
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The source’s display name.
	// A source’s display name must be unique amongst its siblings, for example,
	// two sources with the same parent can't share the same display name.
	// The display name must start and end with a letter or digit, may contain
	// letters, digits, spaces, hyphens, and underscores, and can be no longer
	// than 32 characters. This is captured by the regular expression:
	// [\p{L}\p{N}]({\p{L}\p{N}_- ]{0,30}[\p{L}\p{N}])?.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// The description of the source (max of 1024 characters).
	// Example:
	// "Cloud Security Scanner is a web security scanner for common
	// vulnerabilities in App Engine applications. It can automatically
	// scan and detect four common vulnerabilities, including cross-site-scripting
	// (XSS), Flash injection, mixed content (HTTP in HTTPS), and
	// outdated/insecure libraries."
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Source) Reset()         { *m = Source{} }
func (m *Source) String() string { return proto.CompactTextString(m) }
func (*Source) ProtoMessage()    {}
func (*Source) Descriptor() ([]byte, []int) {
	return fileDescriptor_source_5ac72ab64c788cdd, []int{0}
}
func (m *Source) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Source.Unmarshal(m, b)
}
func (m *Source) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Source.Marshal(b, m, deterministic)
}
func (dst *Source) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Source.Merge(dst, src)
}
func (m *Source) XXX_Size() int {
	return xxx_messageInfo_Source.Size(m)
}
func (m *Source) XXX_DiscardUnknown() {
	xxx_messageInfo_Source.DiscardUnknown(m)
}

var xxx_messageInfo_Source proto.InternalMessageInfo

func (m *Source) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Source) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Source) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*Source)(nil), "google.cloud.securitycenter.v1.Source")
}

func init() {
	proto.RegisterFile("google/cloud/securitycenter/v1/source.proto", fileDescriptor_source_5ac72ab64c788cdd)
}

var fileDescriptor_source_5ac72ab64c788cdd = []byte{
	// 241 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0xd9, 0xba, 0x16, 0x4d, 0x3d, 0x48, 0x4e, 0x45, 0xa4, 0xd4, 0x9e, 0x04, 0x21, 0x61,
	0xf1, 0xe8, 0xcd, 0x1e, 0x04, 0x11, 0x11, 0x0b, 0x1e, 0xbc, 0x48, 0xcc, 0x0e, 0x21, 0x90, 0x66,
	0x42, 0x92, 0x2d, 0xf4, 0x41, 0x7c, 0x09, 0x9f, 0x52, 0x3a, 0x09, 0xc8, 0x1e, 0xf4, 0x16, 0xfe,
	0xff, 0xcb, 0x37, 0xc3, 0xb0, 0x1b, 0x83, 0x68, 0x1c, 0x48, 0xed, 0x70, 0xe8, 0x65, 0x02, 0x3d,
	0x44, 0x9b, 0xf7, 0x1a, 0x7c, 0x86, 0x28, 0x77, 0x9d, 0x4c, 0x38, 0x44, 0x0d, 0x22, 0x44, 0xcc,
	0xc8, 0x17, 0x05, 0x16, 0x04, 0x8b, 0x31, 0x2c, 0x76, 0xdd, 0xc5, 0x65, 0x95, 0xa9, 0x60, 0xa5,
	0xf2, 0x1e, 0xb3, 0xca, 0x16, 0x7d, 0x2a, 0xbf, 0x57, 0x86, 0x4d, 0x37, 0x64, 0xe3, 0x9c, 0xb5,
	0x5e, 0x6d, 0x61, 0xde, 0x2c, 0x9b, 0xeb, 0xd3, 0x57, 0x7a, 0xf3, 0x2b, 0x76, 0xd6, 0xdb, 0x14,
	0x9c, 0xda, 0x7f, 0x50, 0x37, 0xa1, 0x6e, 0x56, 0xb3, 0xe7, 0x03, 0xb2, 0x64, 0xb3, 0x1e, 0x92,
	0x8e, 0x36, 0x1c, 0xb4, 0xf3, 0xa3, 0x4a, 0xfc, 0x46, 0x8f, 0xed, 0x49, 0x7b, 0x7e, 0x7c, 0xff,
	0xd5, 0xb0, 0x95, 0xc6, 0xad, 0xf8, 0x7f, 0xdb, 0x97, 0xe6, 0xfd, 0xa9, 0x12, 0x06, 0x9d, 0xf2,
	0x46, 0x60, 0x34, 0xd2, 0x80, 0xa7, 0x6d, 0x65, 0xa9, 0x54, 0xb0, 0xe9, 0xaf, 0xdb, 0xdc, 0x8d,
	0x93, 0xef, 0xc9, 0xe2, 0xa1, 0xe8, 0xd6, 0x34, 0x70, 0x53, 0xdb, 0x75, 0x19, 0xf8, 0xd6, 0x7d,
	0x4e, 0xc9, 0x7c, 0xfb, 0x13, 0x00, 0x00, 0xff, 0xff, 0xf7, 0x1e, 0xb8, 0x09, 0x74, 0x01, 0x00,
	0x00,
}
