// Code generated by protoc-gen-go. DO NOT EDIT.
// source: google/ads/googleads/v3/services/search_term_view_service.proto

package services

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	resources "google.golang.org/genproto/googleapis/ads/googleads/v3/resources"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Request message for [SearchTermViewService.GetSearchTermView][google.ads.googleads.v3.services.SearchTermViewService.GetSearchTermView].
type GetSearchTermViewRequest struct {
	// Required. The resource name of the search term view to fetch.
	ResourceName         string   `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSearchTermViewRequest) Reset()         { *m = GetSearchTermViewRequest{} }
func (m *GetSearchTermViewRequest) String() string { return proto.CompactTextString(m) }
func (*GetSearchTermViewRequest) ProtoMessage()    {}
func (*GetSearchTermViewRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1667b609515952c8, []int{0}
}

func (m *GetSearchTermViewRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSearchTermViewRequest.Unmarshal(m, b)
}
func (m *GetSearchTermViewRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSearchTermViewRequest.Marshal(b, m, deterministic)
}
func (m *GetSearchTermViewRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSearchTermViewRequest.Merge(m, src)
}
func (m *GetSearchTermViewRequest) XXX_Size() int {
	return xxx_messageInfo_GetSearchTermViewRequest.Size(m)
}
func (m *GetSearchTermViewRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSearchTermViewRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSearchTermViewRequest proto.InternalMessageInfo

func (m *GetSearchTermViewRequest) GetResourceName() string {
	if m != nil {
		return m.ResourceName
	}
	return ""
}

func init() {
	proto.RegisterType((*GetSearchTermViewRequest)(nil), "google.ads.googleads.v3.services.GetSearchTermViewRequest")
}

func init() {
	proto.RegisterFile("google/ads/googleads/v3/services/search_term_view_service.proto", fileDescriptor_1667b609515952c8)
}

var fileDescriptor_1667b609515952c8 = []byte{
	// 417 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x4f, 0x6b, 0xd4, 0x40,
	0x14, 0x27, 0x29, 0x08, 0x06, 0x3d, 0x18, 0x10, 0x97, 0x28, 0xb8, 0x94, 0x1e, 0x4a, 0x0f, 0x33,
	0xd4, 0x5c, 0x64, 0x44, 0x64, 0x16, 0x61, 0xf5, 0x22, 0xa5, 0x95, 0x1c, 0x24, 0x10, 0xa6, 0xc9,
	0x33, 0x1d, 0x48, 0x32, 0xeb, 0xbc, 0xd9, 0xf4, 0x20, 0x1e, 0x14, 0xbf, 0x81, 0xdf, 0xc0, 0xa3,
	0x1f, 0xa5, 0xe0, 0xc9, 0x9b, 0x27, 0x0f, 0x9e, 0xfc, 0x14, 0x92, 0x9d, 0x4c, 0xda, 0xd0, 0x86,
	0xbd, 0xfd, 0xc8, 0xef, 0xdf, 0xbc, 0xf7, 0x12, 0xbc, 0x28, 0x95, 0x2a, 0x2b, 0xa0, 0xa2, 0x40,
	0x6a, 0x61, 0x87, 0xda, 0x98, 0x22, 0xe8, 0x56, 0xe6, 0x80, 0x14, 0x41, 0xe8, 0xfc, 0x2c, 0x33,
	0xa0, 0xeb, 0xac, 0x95, 0x70, 0x9e, 0xf5, 0x0c, 0x59, 0x69, 0x65, 0x54, 0x38, 0xb7, 0x2e, 0x22,
	0x0a, 0x24, 0x43, 0x00, 0x69, 0x63, 0xe2, 0x02, 0xa2, 0xa7, 0x53, 0x15, 0x1a, 0x50, 0xad, 0xf5,
	0x4d, 0x1d, 0x36, 0x3b, 0x7a, 0xe4, 0x9c, 0x2b, 0x49, 0x45, 0xd3, 0x28, 0x23, 0x8c, 0x54, 0x0d,
	0xf6, 0xec, 0x83, 0x2b, 0x6c, 0x5e, 0x49, 0x68, 0x4c, 0x4f, 0x3c, 0xbe, 0x42, 0xbc, 0x97, 0x50,
	0x15, 0xd9, 0x29, 0x9c, 0x89, 0x56, 0x2a, 0x6d, 0x05, 0xbb, 0x2f, 0x83, 0xd9, 0x12, 0xcc, 0xc9,
	0xa6, 0xf4, 0x2d, 0xe8, 0x3a, 0x91, 0x70, 0x7e, 0x0c, 0x1f, 0xd6, 0x80, 0x26, 0xdc, 0x0f, 0xee,
	0xba, 0x77, 0x65, 0x8d, 0xa8, 0x61, 0xe6, 0xcd, 0xbd, 0xfd, 0xdb, 0x8b, 0x9d, 0x3f, 0xdc, 0x3f,
	0xbe, 0xe3, 0x98, 0x37, 0xa2, 0x86, 0x27, 0x5f, 0xfd, 0xe0, 0xfe, 0x38, 0xe3, 0xc4, 0x8e, 0x1c,
	0xfe, 0xf4, 0x82, 0x7b, 0xd7, 0x0a, 0x42, 0x46, 0xb6, 0xad, 0x8a, 0x4c, 0xbd, 0x2a, 0x3a, 0x9c,
	0xf4, 0x0e, 0x4b, 0x24, 0x63, 0xe7, 0xee, 0xeb, 0xdf, 0x7c, 0x3c, 0xc9, 0x97, 0x5f, 0x7f, 0xbf,
	0xf9, 0x71, 0x78, 0xd8, 0xad, 0xfe, 0xe3, 0x88, 0x79, 0x9e, 0xaf, 0xd1, 0xa8, 0x1a, 0x34, 0xd2,
	0x83, 0xfe, 0x16, 0x2e, 0x06, 0xe9, 0xc1, 0xa7, 0xe8, 0xe1, 0x05, 0x9f, 0x5d, 0x96, 0xf6, 0x68,
	0x25, 0x91, 0xe4, 0xaa, 0x5e, 0x7c, 0xf6, 0x83, 0xbd, 0x5c, 0xd5, 0x5b, 0x87, 0x5b, 0x44, 0x37,
	0x2e, 0xeb, 0xa8, 0xbb, 0xc8, 0x91, 0xf7, 0xee, 0x55, 0xef, 0x2f, 0x55, 0x25, 0x9a, 0x92, 0x28,
	0x5d, 0xd2, 0x12, 0x9a, 0xcd, 0xbd, 0xe8, 0x65, 0xe3, 0xf4, 0x7f, 0xfa, 0xcc, 0x81, 0xef, 0xfe,
	0xce, 0x92, 0xf3, 0x1f, 0xfe, 0x7c, 0x69, 0x03, 0x79, 0x81, 0xc4, 0xc2, 0x0e, 0x25, 0x31, 0xe9,
	0x8b, 0xf1, 0xc2, 0x49, 0x52, 0x5e, 0x60, 0x3a, 0x48, 0xd2, 0x24, 0x4e, 0x9d, 0xe4, 0x9f, 0xbf,
	0x67, 0xbf, 0x33, 0xc6, 0x0b, 0x64, 0x6c, 0x10, 0x31, 0x96, 0xc4, 0x8c, 0x39, 0xd9, 0xe9, 0xad,
	0xcd, 0x3b, 0xe3, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x58, 0xa3, 0xde, 0xec, 0x4e, 0x03, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SearchTermViewServiceClient is the client API for SearchTermViewService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SearchTermViewServiceClient interface {
	// Returns the attributes of the requested search term view.
	GetSearchTermView(ctx context.Context, in *GetSearchTermViewRequest, opts ...grpc.CallOption) (*resources.SearchTermView, error)
}

type searchTermViewServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchTermViewServiceClient(cc grpc.ClientConnInterface) SearchTermViewServiceClient {
	return &searchTermViewServiceClient{cc}
}

func (c *searchTermViewServiceClient) GetSearchTermView(ctx context.Context, in *GetSearchTermViewRequest, opts ...grpc.CallOption) (*resources.SearchTermView, error) {
	out := new(resources.SearchTermView)
	err := c.cc.Invoke(ctx, "/google.ads.googleads.v3.services.SearchTermViewService/GetSearchTermView", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchTermViewServiceServer is the server API for SearchTermViewService service.
type SearchTermViewServiceServer interface {
	// Returns the attributes of the requested search term view.
	GetSearchTermView(context.Context, *GetSearchTermViewRequest) (*resources.SearchTermView, error)
}

// UnimplementedSearchTermViewServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSearchTermViewServiceServer struct {
}

func (*UnimplementedSearchTermViewServiceServer) GetSearchTermView(ctx context.Context, req *GetSearchTermViewRequest) (*resources.SearchTermView, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSearchTermView not implemented")
}

func RegisterSearchTermViewServiceServer(s *grpc.Server, srv SearchTermViewServiceServer) {
	s.RegisterService(&_SearchTermViewService_serviceDesc, srv)
}

func _SearchTermViewService_GetSearchTermView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSearchTermViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchTermViewServiceServer).GetSearchTermView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.ads.googleads.v3.services.SearchTermViewService/GetSearchTermView",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchTermViewServiceServer).GetSearchTermView(ctx, req.(*GetSearchTermViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SearchTermViewService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "google.ads.googleads.v3.services.SearchTermViewService",
	HandlerType: (*SearchTermViewServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSearchTermView",
			Handler:    _SearchTermViewService_GetSearchTermView_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "google/ads/googleads/v3/services/search_term_view_service.proto",
}
