// Code generated by protoc-gen-go. DO NOT EDIT.
// source: google/ads/googleads/v1/services/ad_schedule_view_service.proto

package services

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	resources "google.golang.org/genproto/googleapis/ads/googleads/v1/resources"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Request message for [AdScheduleViewService.GetAdScheduleView][google.ads.googleads.v1.services.AdScheduleViewService.GetAdScheduleView].
type GetAdScheduleViewRequest struct {
	// Required. The resource name of the ad schedule view to fetch.
	ResourceName         string   `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAdScheduleViewRequest) Reset()         { *m = GetAdScheduleViewRequest{} }
func (m *GetAdScheduleViewRequest) String() string { return proto.CompactTextString(m) }
func (*GetAdScheduleViewRequest) ProtoMessage()    {}
func (*GetAdScheduleViewRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6e0ec29d39ff4cc, []int{0}
}

func (m *GetAdScheduleViewRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAdScheduleViewRequest.Unmarshal(m, b)
}
func (m *GetAdScheduleViewRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAdScheduleViewRequest.Marshal(b, m, deterministic)
}
func (m *GetAdScheduleViewRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAdScheduleViewRequest.Merge(m, src)
}
func (m *GetAdScheduleViewRequest) XXX_Size() int {
	return xxx_messageInfo_GetAdScheduleViewRequest.Size(m)
}
func (m *GetAdScheduleViewRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAdScheduleViewRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAdScheduleViewRequest proto.InternalMessageInfo

func (m *GetAdScheduleViewRequest) GetResourceName() string {
	if m != nil {
		return m.ResourceName
	}
	return ""
}

func init() {
	proto.RegisterType((*GetAdScheduleViewRequest)(nil), "google.ads.googleads.v1.services.GetAdScheduleViewRequest")
}

func init() {
	proto.RegisterFile("google/ads/googleads/v1/services/ad_schedule_view_service.proto", fileDescriptor_b6e0ec29d39ff4cc)
}

var fileDescriptor_b6e0ec29d39ff4cc = []byte{
	// 430 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xbf, 0x8a, 0xd4, 0x40,
	0x18, 0x67, 0x23, 0x08, 0x06, 0x2d, 0x0c, 0x88, 0x6b, 0x14, 0x5c, 0x8e, 0x03, 0xf5, 0x8a, 0x19,
	0xe2, 0x35, 0x32, 0x22, 0x32, 0xdb, 0xac, 0x36, 0x72, 0x78, 0xb2, 0x85, 0x04, 0xc2, 0x5c, 0xe6,
	0x33, 0x37, 0x90, 0x64, 0x62, 0xbe, 0x24, 0x57, 0x88, 0x85, 0xe2, 0x1b, 0xf8, 0x06, 0x96, 0x3e,
	0xca, 0x81, 0x95, 0x9d, 0x95, 0x85, 0x95, 0x8f, 0x60, 0x25, 0xb9, 0x99, 0xc9, 0x6d, 0xf4, 0xc2,
	0x76, 0x3f, 0xe6, 0xf7, 0xe7, 0xfb, 0x37, 0xfe, 0xd3, 0x4c, 0xeb, 0x2c, 0x07, 0x2a, 0x24, 0x52,
	0x03, 0x7b, 0xd4, 0x45, 0x14, 0xa1, 0xee, 0x54, 0x0a, 0x48, 0x85, 0x4c, 0x30, 0x3d, 0x06, 0xd9,
	0xe6, 0x90, 0x74, 0x0a, 0x4e, 0x12, 0xcb, 0x90, 0xaa, 0xd6, 0x8d, 0x0e, 0x16, 0xc6, 0x45, 0x84,
	0x44, 0x32, 0x04, 0x90, 0x2e, 0x22, 0x2e, 0x20, 0x7c, 0x34, 0x55, 0xa2, 0x06, 0xd4, 0x6d, 0x7d,
	0x51, 0x0d, 0x93, 0x1d, 0xde, 0x71, 0xce, 0x4a, 0x51, 0x51, 0x96, 0xba, 0x11, 0x8d, 0xd2, 0x25,
	0x5a, 0xf6, 0xe6, 0x06, 0x9b, 0xe6, 0x0a, 0xca, 0xc6, 0x12, 0x77, 0x37, 0x88, 0x37, 0x0a, 0x72,
	0x99, 0x1c, 0xc1, 0xb1, 0xe8, 0x94, 0xae, 0xad, 0xe0, 0xd6, 0x86, 0xc0, 0x35, 0x61, 0xa8, 0x9d,
	0xca, 0x9f, 0xaf, 0xa0, 0xe1, 0xf2, 0xd0, 0xb6, 0xb3, 0x56, 0x70, 0xf2, 0x12, 0xde, 0xb6, 0x80,
	0x4d, 0xf0, 0xca, 0xbf, 0xe6, 0xd4, 0x49, 0x29, 0x0a, 0x98, 0xcf, 0x16, 0xb3, 0xfb, 0x57, 0x96,
	0xf4, 0x27, 0xf7, 0xfe, 0xf0, 0x07, 0xfe, 0xbd, 0xf3, 0xf1, 0x2d, 0xaa, 0x14, 0x92, 0x54, 0x17,
	0xf4, 0x9f, 0xb8, 0xab, 0x2e, 0xe5, 0x85, 0x28, 0xe0, 0xe1, 0x27, 0xcf, 0xbf, 0x31, 0x16, 0x1c,
	0x9a, 0xcd, 0x05, 0xdf, 0x66, 0xfe, 0xf5, 0xff, 0x9a, 0x09, 0x18, 0xd9, 0xb6, 0x71, 0x32, 0x35,
	0x41, 0x18, 0x4d, 0x7a, 0x87, 0x5b, 0x90, 0xb1, 0x73, 0xe7, 0xf9, 0x0f, 0x3e, 0x9e, 0xfa, 0xe3,
	0xf7, 0x5f, 0x9f, 0xbd, 0xfd, 0x20, 0xea, 0x2f, 0xf8, 0x6e, 0xc4, 0x3c, 0x49, 0x5b, 0x6c, 0x74,
	0x01, 0x35, 0xd2, 0x3d, 0x2a, 0x46, 0x31, 0x48, 0xf7, 0xde, 0x87, 0xb7, 0x4f, 0xf9, 0x7c, 0x6a,
	0x47, 0xcb, 0x0f, 0x9e, 0xbf, 0x9b, 0xea, 0x62, 0xeb, 0x70, 0xcb, 0xf0, 0xc2, 0x65, 0x1d, 0xf4,
	0xd7, 0x3b, 0x98, 0xbd, 0x7e, 0x66, 0xfd, 0x99, 0xce, 0x45, 0x99, 0x11, 0x5d, 0x67, 0x34, 0x83,
	0xf2, 0xec, 0xb6, 0xf4, 0xbc, 0xe2, 0xf4, 0x77, 0x7f, 0xec, 0xc0, 0x17, 0xef, 0xd2, 0x8a, 0xf3,
	0xaf, 0xde, 0x62, 0x65, 0x02, 0xb9, 0x44, 0x62, 0x60, 0x8f, 0xd6, 0x11, 0xb1, 0x85, 0xf1, 0xd4,
	0x49, 0x62, 0x2e, 0x31, 0x1e, 0x24, 0xf1, 0x3a, 0x8a, 0x9d, 0xe4, 0xb7, 0xb7, 0x6b, 0xde, 0x19,
	0xe3, 0x12, 0x19, 0x1b, 0x44, 0x8c, 0xad, 0x23, 0xc6, 0x9c, 0xec, 0xe8, 0xf2, 0x59, 0x9f, 0xfb,
	0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x0e, 0x1b, 0xf7, 0x0a, 0x95, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AdScheduleViewServiceClient is the client API for AdScheduleViewService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AdScheduleViewServiceClient interface {
	// Returns the requested ad schedule view in full detail.
	GetAdScheduleView(ctx context.Context, in *GetAdScheduleViewRequest, opts ...grpc.CallOption) (*resources.AdScheduleView, error)
}

type adScheduleViewServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdScheduleViewServiceClient(cc grpc.ClientConnInterface) AdScheduleViewServiceClient {
	return &adScheduleViewServiceClient{cc}
}

func (c *adScheduleViewServiceClient) GetAdScheduleView(ctx context.Context, in *GetAdScheduleViewRequest, opts ...grpc.CallOption) (*resources.AdScheduleView, error) {
	out := new(resources.AdScheduleView)
	err := c.cc.Invoke(ctx, "/google.ads.googleads.v1.services.AdScheduleViewService/GetAdScheduleView", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdScheduleViewServiceServer is the server API for AdScheduleViewService service.
type AdScheduleViewServiceServer interface {
	// Returns the requested ad schedule view in full detail.
	GetAdScheduleView(context.Context, *GetAdScheduleViewRequest) (*resources.AdScheduleView, error)
}

// UnimplementedAdScheduleViewServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAdScheduleViewServiceServer struct {
}

func (*UnimplementedAdScheduleViewServiceServer) GetAdScheduleView(ctx context.Context, req *GetAdScheduleViewRequest) (*resources.AdScheduleView, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAdScheduleView not implemented")
}

func RegisterAdScheduleViewServiceServer(s *grpc.Server, srv AdScheduleViewServiceServer) {
	s.RegisterService(&_AdScheduleViewService_serviceDesc, srv)
}

func _AdScheduleViewService_GetAdScheduleView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdScheduleViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdScheduleViewServiceServer).GetAdScheduleView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.ads.googleads.v1.services.AdScheduleViewService/GetAdScheduleView",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdScheduleViewServiceServer).GetAdScheduleView(ctx, req.(*GetAdScheduleViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AdScheduleViewService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "google.ads.googleads.v1.services.AdScheduleViewService",
	HandlerType: (*AdScheduleViewServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAdScheduleView",
			Handler:    _AdScheduleViewService_GetAdScheduleView_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "google/ads/googleads/v1/services/ad_schedule_view_service.proto",
}
