// Code generated by protoc-gen-go. DO NOT EDIT.
// source: google/ads/googleads/v1/services/detail_placement_view_service.proto

package services

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	resources "google.golang.org/genproto/googleapis/ads/googleads/v1/resources"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Request message for [DetailPlacementViewService.GetDetailPlacementView][google.ads.googleads.v1.services.DetailPlacementViewService.GetDetailPlacementView].
type GetDetailPlacementViewRequest struct {
	// The resource name of the Detail Placement view to fetch.
	ResourceName         string   `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDetailPlacementViewRequest) Reset()         { *m = GetDetailPlacementViewRequest{} }
func (m *GetDetailPlacementViewRequest) String() string { return proto.CompactTextString(m) }
func (*GetDetailPlacementViewRequest) ProtoMessage()    {}
func (*GetDetailPlacementViewRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f5548d46c4dece9, []int{0}
}

func (m *GetDetailPlacementViewRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDetailPlacementViewRequest.Unmarshal(m, b)
}
func (m *GetDetailPlacementViewRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDetailPlacementViewRequest.Marshal(b, m, deterministic)
}
func (m *GetDetailPlacementViewRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDetailPlacementViewRequest.Merge(m, src)
}
func (m *GetDetailPlacementViewRequest) XXX_Size() int {
	return xxx_messageInfo_GetDetailPlacementViewRequest.Size(m)
}
func (m *GetDetailPlacementViewRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDetailPlacementViewRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDetailPlacementViewRequest proto.InternalMessageInfo

func (m *GetDetailPlacementViewRequest) GetResourceName() string {
	if m != nil {
		return m.ResourceName
	}
	return ""
}

func init() {
	proto.RegisterType((*GetDetailPlacementViewRequest)(nil), "google.ads.googleads.v1.services.GetDetailPlacementViewRequest")
}

func init() {
	proto.RegisterFile("google/ads/googleads/v1/services/detail_placement_view_service.proto", fileDescriptor_9f5548d46c4dece9)
}

var fileDescriptor_9f5548d46c4dece9 = []byte{
	// 399 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xc1, 0xaa, 0xd3, 0x40,
	0x14, 0x25, 0x11, 0x04, 0x83, 0x6e, 0xb2, 0xd0, 0x12, 0x15, 0x4b, 0xed, 0x42, 0xba, 0x98, 0x21,
	0x0a, 0x45, 0x46, 0xaa, 0xa4, 0x14, 0xea, 0x4a, 0x4a, 0x85, 0x2c, 0x24, 0x10, 0xc6, 0xe4, 0x12,
	0x06, 0x92, 0x99, 0x98, 0x99, 0xa6, 0x0b, 0x71, 0xe3, 0xc2, 0x9d, 0x2b, 0xff, 0xc0, 0xe5, 0xfb,
	0x94, 0xee, 0x1e, 0xef, 0x17, 0xde, 0xea, 0x7d, 0xc5, 0x23, 0x9d, 0x4c, 0xfa, 0x0a, 0xcd, 0xeb,
	0xee, 0x30, 0xf7, 0xdc, 0x73, 0xee, 0x3d, 0x77, 0x9c, 0x45, 0x26, 0x44, 0x96, 0x03, 0xa6, 0xa9,
	0xc4, 0x1a, 0x36, 0xa8, 0xf6, 0xb1, 0x84, 0xaa, 0x66, 0x09, 0x48, 0x9c, 0x82, 0xa2, 0x2c, 0x8f,
	0xcb, 0x9c, 0x26, 0x50, 0x00, 0x57, 0x71, 0xcd, 0x60, 0x1b, 0xb7, 0x65, 0x54, 0x56, 0x42, 0x09,
	0x77, 0xa8, 0x5b, 0x11, 0x4d, 0x25, 0xea, 0x54, 0x50, 0xed, 0x23, 0xa3, 0xe2, 0xcd, 0xfa, 0x7c,
	0x2a, 0x90, 0x62, 0x53, 0xf5, 0x1a, 0x69, 0x03, 0xef, 0x85, 0x69, 0x2f, 0x19, 0xa6, 0x9c, 0x0b,
	0x45, 0x15, 0x13, 0x5c, 0xb6, 0xd5, 0x67, 0x77, 0xaa, 0x49, 0xce, 0x80, 0x2b, 0x5d, 0x18, 0x2d,
	0x9c, 0x97, 0x4b, 0x50, 0x8b, 0xbd, 0xf0, 0xca, 0xe8, 0x86, 0x0c, 0xb6, 0x6b, 0xf8, 0xb1, 0x01,
	0xa9, 0xdc, 0xd7, 0xce, 0x13, 0x33, 0x40, 0xcc, 0x69, 0x01, 0x03, 0x6b, 0x68, 0xbd, 0x79, 0xb4,
	0x7e, 0x6c, 0x1e, 0xbf, 0xd0, 0x02, 0xde, 0xfe, 0xb5, 0x1d, 0xef, 0x84, 0xc6, 0x57, 0xbd, 0x9b,
	0x7b, 0x69, 0x39, 0x4f, 0x4f, 0xbb, 0xb8, 0x9f, 0xd0, 0xb9, 0x60, 0xd0, 0xbd, 0xf3, 0x79, 0xd3,
	0x5e, 0x81, 0x2e, 0x37, 0x74, 0xa2, 0x7d, 0xf4, 0xf1, 0xf7, 0xd5, 0xf5, 0x3f, 0xfb, 0xbd, 0x3b,
	0x6d, 0x22, 0xfe, 0x79, 0xb4, 0xe2, 0x2c, 0xd9, 0x48, 0x25, 0x0a, 0xa8, 0x24, 0x9e, 0xb4, 0x99,
	0x1f, 0xf5, 0x4a, 0x3c, 0xf9, 0xe5, 0x3d, 0xdf, 0x05, 0x83, 0x83, 0x5d, 0x8b, 0x4a, 0x26, 0x51,
	0x22, 0x8a, 0xf9, 0x1f, 0xdb, 0x19, 0x27, 0xa2, 0x38, 0xbb, 0xdb, 0xfc, 0x55, 0x7f, 0x6a, 0xab,
	0xe6, 0x3e, 0x2b, 0xeb, 0xdb, 0xe7, 0x56, 0x24, 0x13, 0x39, 0xe5, 0x19, 0x12, 0x55, 0x86, 0x33,
	0xe0, 0xfb, 0xeb, 0xe1, 0x83, 0x6d, 0xff, 0xf7, 0xfc, 0x60, 0xc0, 0x7f, 0xfb, 0xc1, 0x32, 0x08,
	0x2e, 0xec, 0xe1, 0x52, 0x0b, 0x06, 0xa9, 0x44, 0x1a, 0x36, 0x28, 0xf4, 0x51, 0x6b, 0x2c, 0x77,
	0x86, 0x12, 0x05, 0xa9, 0x8c, 0x3a, 0x4a, 0x14, 0xfa, 0x91, 0xa1, 0xdc, 0xd8, 0x63, 0xfd, 0x4e,
	0x48, 0x90, 0x4a, 0x42, 0x3a, 0x12, 0x21, 0xa1, 0x4f, 0x88, 0xa1, 0x7d, 0x7f, 0xb8, 0x9f, 0xf3,
	0xdd, 0x6d, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9b, 0x76, 0x48, 0xff, 0x45, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DetailPlacementViewServiceClient is the client API for DetailPlacementViewService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DetailPlacementViewServiceClient interface {
	// Returns the requested Detail Placement view in full detail.
	GetDetailPlacementView(ctx context.Context, in *GetDetailPlacementViewRequest, opts ...grpc.CallOption) (*resources.DetailPlacementView, error)
}

type detailPlacementViewServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDetailPlacementViewServiceClient(cc grpc.ClientConnInterface) DetailPlacementViewServiceClient {
	return &detailPlacementViewServiceClient{cc}
}

func (c *detailPlacementViewServiceClient) GetDetailPlacementView(ctx context.Context, in *GetDetailPlacementViewRequest, opts ...grpc.CallOption) (*resources.DetailPlacementView, error) {
	out := new(resources.DetailPlacementView)
	err := c.cc.Invoke(ctx, "/google.ads.googleads.v1.services.DetailPlacementViewService/GetDetailPlacementView", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DetailPlacementViewServiceServer is the server API for DetailPlacementViewService service.
type DetailPlacementViewServiceServer interface {
	// Returns the requested Detail Placement view in full detail.
	GetDetailPlacementView(context.Context, *GetDetailPlacementViewRequest) (*resources.DetailPlacementView, error)
}

// UnimplementedDetailPlacementViewServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDetailPlacementViewServiceServer struct {
}

func (*UnimplementedDetailPlacementViewServiceServer) GetDetailPlacementView(ctx context.Context, req *GetDetailPlacementViewRequest) (*resources.DetailPlacementView, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDetailPlacementView not implemented")
}

func RegisterDetailPlacementViewServiceServer(s *grpc.Server, srv DetailPlacementViewServiceServer) {
	s.RegisterService(&_DetailPlacementViewService_serviceDesc, srv)
}

func _DetailPlacementViewService_GetDetailPlacementView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDetailPlacementViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DetailPlacementViewServiceServer).GetDetailPlacementView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.ads.googleads.v1.services.DetailPlacementViewService/GetDetailPlacementView",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DetailPlacementViewServiceServer).GetDetailPlacementView(ctx, req.(*GetDetailPlacementViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DetailPlacementViewService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "google.ads.googleads.v1.services.DetailPlacementViewService",
	HandlerType: (*DetailPlacementViewServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDetailPlacementView",
			Handler:    _DetailPlacementViewService_GetDetailPlacementView_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "google/ads/googleads/v1/services/detail_placement_view_service.proto",
}
