// Code generated by protoc-gen-go. DO NOT EDIT.
// source: google/ads/googleads/v1/services/topic_constant_service.proto

package services

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	resources "google.golang.org/genproto/googleapis/ads/googleads/v1/resources"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Request message for [TopicConstantService.GetTopicConstant][google.ads.googleads.v1.services.TopicConstantService.GetTopicConstant].
type GetTopicConstantRequest struct {
	// Resource name of the Topic to fetch.
	ResourceName         string   `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTopicConstantRequest) Reset()         { *m = GetTopicConstantRequest{} }
func (m *GetTopicConstantRequest) String() string { return proto.CompactTextString(m) }
func (*GetTopicConstantRequest) ProtoMessage()    {}
func (*GetTopicConstantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_49736dbc2500820f, []int{0}
}

func (m *GetTopicConstantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTopicConstantRequest.Unmarshal(m, b)
}
func (m *GetTopicConstantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTopicConstantRequest.Marshal(b, m, deterministic)
}
func (m *GetTopicConstantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTopicConstantRequest.Merge(m, src)
}
func (m *GetTopicConstantRequest) XXX_Size() int {
	return xxx_messageInfo_GetTopicConstantRequest.Size(m)
}
func (m *GetTopicConstantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTopicConstantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTopicConstantRequest proto.InternalMessageInfo

func (m *GetTopicConstantRequest) GetResourceName() string {
	if m != nil {
		return m.ResourceName
	}
	return ""
}

func init() {
	proto.RegisterType((*GetTopicConstantRequest)(nil), "google.ads.googleads.v1.services.GetTopicConstantRequest")
}

func init() {
	proto.RegisterFile("google/ads/googleads/v1/services/topic_constant_service.proto", fileDescriptor_49736dbc2500820f)
}

var fileDescriptor_49736dbc2500820f = []byte{
	// 374 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x4f, 0x4a, 0xc3, 0x40,
	0x14, 0xc6, 0x49, 0x04, 0xc1, 0xa0, 0x20, 0x41, 0x68, 0x8d, 0x2e, 0x4a, 0x2d, 0x22, 0x22, 0x33,
	0x46, 0x41, 0x70, 0xa4, 0x42, 0xea, 0xa2, 0xae, 0xa4, 0x54, 0xe9, 0x42, 0x02, 0x65, 0x4c, 0x86,
	0x10, 0x68, 0x66, 0x62, 0xde, 0xb4, 0x1b, 0x11, 0xc4, 0x2b, 0x78, 0x03, 0x97, 0x82, 0x17, 0xe9,
	0xd6, 0x23, 0xe8, 0xca, 0x53, 0x48, 0x9a, 0x4c, 0xda, 0xaa, 0xa1, 0xbb, 0x8f, 0x37, 0xdf, 0xef,
	0x7b, 0x7f, 0x12, 0xa3, 0x19, 0x08, 0x11, 0x0c, 0x18, 0xa6, 0x3e, 0xe0, 0x4c, 0xa6, 0x6a, 0x64,
	0x63, 0x60, 0xc9, 0x28, 0xf4, 0x18, 0x60, 0x29, 0xe2, 0xd0, 0xeb, 0x7b, 0x82, 0x83, 0xa4, 0x5c,
	0xf6, 0xf3, 0x3a, 0x8a, 0x13, 0x21, 0x85, 0x59, 0xcb, 0x18, 0x44, 0x7d, 0x40, 0x05, 0x8e, 0x46,
	0x36, 0x52, 0xb8, 0x75, 0x52, 0xd6, 0x20, 0x61, 0x20, 0x86, 0xc9, 0xdf, 0x0e, 0x59, 0xb2, 0xb5,
	0xad, 0xb8, 0x38, 0xc4, 0x94, 0x73, 0x21, 0xa9, 0x0c, 0x05, 0x87, 0xfc, 0xb5, 0x32, 0xf3, 0xea,
	0x0d, 0x42, 0xa6, 0xb0, 0xfa, 0xb9, 0x51, 0x69, 0x33, 0x79, 0x93, 0x26, 0x5e, 0xe4, 0x81, 0x5d,
	0x76, 0x3f, 0x64, 0x20, 0xcd, 0x1d, 0x63, 0x4d, 0xf5, 0xec, 0x73, 0x1a, 0xb1, 0xaa, 0x56, 0xd3,
	0xf6, 0x56, 0xba, 0xab, 0xaa, 0x78, 0x45, 0x23, 0x76, 0xf4, 0xa9, 0x19, 0x1b, 0x73, 0xf4, 0x75,
	0xb6, 0x88, 0xf9, 0xae, 0x19, 0xeb, 0xbf, 0x93, 0xcd, 0x53, 0xb4, 0x68, 0x7f, 0x54, 0x32, 0x8d,
	0x75, 0x58, 0x8a, 0x16, 0x87, 0x41, 0x73, 0x60, 0xfd, 0xe0, 0xf9, 0xe3, 0xeb, 0x45, 0xdf, 0x35,
	0x1b, 0xe9, 0xf5, 0x1e, 0xe6, 0x56, 0x69, 0xca, 0x59, 0x27, 0xe0, 0xfd, 0x47, 0x6b, 0x6b, 0xec,
	0x54, 0xa7, 0xb1, 0xb9, 0x8a, 0x43, 0x40, 0x9e, 0x88, 0x5a, 0x4f, 0xba, 0xd1, 0xf0, 0x44, 0xb4,
	0x70, 0xfa, 0xd6, 0xe6, 0x7f, 0xb7, 0xe8, 0xa4, 0x97, 0xee, 0x68, 0xb7, 0x97, 0x39, 0x1e, 0x88,
	0x01, 0xe5, 0x01, 0x12, 0x49, 0x80, 0x03, 0xc6, 0x27, 0xdf, 0x01, 0x4f, 0x1b, 0x96, 0xff, 0x5a,
	0x67, 0x4a, 0xbc, 0xea, 0x4b, 0x6d, 0xc7, 0x79, 0xd3, 0x6b, 0xed, 0x2c, 0xd0, 0xf1, 0x01, 0x65,
	0x32, 0x55, 0x3d, 0x1b, 0xe5, 0x8d, 0x61, 0xac, 0x2c, 0xae, 0xe3, 0x83, 0x5b, 0x58, 0xdc, 0x9e,
	0xed, 0x2a, 0xcb, 0xb7, 0xde, 0xc8, 0xea, 0x84, 0x38, 0x3e, 0x10, 0x52, 0x98, 0x08, 0xe9, 0xd9,
	0x84, 0x28, 0xdb, 0xdd, 0xf2, 0x64, 0xce, 0xe3, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd4, 0x62,
	0x66, 0x3f, 0x01, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TopicConstantServiceClient is the client API for TopicConstantService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TopicConstantServiceClient interface {
	// Returns the requested topic constant in full detail.
	GetTopicConstant(ctx context.Context, in *GetTopicConstantRequest, opts ...grpc.CallOption) (*resources.TopicConstant, error)
}

type topicConstantServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTopicConstantServiceClient(cc grpc.ClientConnInterface) TopicConstantServiceClient {
	return &topicConstantServiceClient{cc}
}

func (c *topicConstantServiceClient) GetTopicConstant(ctx context.Context, in *GetTopicConstantRequest, opts ...grpc.CallOption) (*resources.TopicConstant, error) {
	out := new(resources.TopicConstant)
	err := c.cc.Invoke(ctx, "/google.ads.googleads.v1.services.TopicConstantService/GetTopicConstant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TopicConstantServiceServer is the server API for TopicConstantService service.
type TopicConstantServiceServer interface {
	// Returns the requested topic constant in full detail.
	GetTopicConstant(context.Context, *GetTopicConstantRequest) (*resources.TopicConstant, error)
}

// UnimplementedTopicConstantServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTopicConstantServiceServer struct {
}

func (*UnimplementedTopicConstantServiceServer) GetTopicConstant(ctx context.Context, req *GetTopicConstantRequest) (*resources.TopicConstant, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopicConstant not implemented")
}

func RegisterTopicConstantServiceServer(s *grpc.Server, srv TopicConstantServiceServer) {
	s.RegisterService(&_TopicConstantService_serviceDesc, srv)
}

func _TopicConstantService_GetTopicConstant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopicConstantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopicConstantServiceServer).GetTopicConstant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.ads.googleads.v1.services.TopicConstantService/GetTopicConstant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopicConstantServiceServer).GetTopicConstant(ctx, req.(*GetTopicConstantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TopicConstantService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "google.ads.googleads.v1.services.TopicConstantService",
	HandlerType: (*TopicConstantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTopicConstant",
			Handler:    _TopicConstantService_GetTopicConstant_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "google/ads/googleads/v1/services/topic_constant_service.proto",
}
